import os.path

# import build environment and build directory
Import('env buildDir')

# setup build directory
buildDir = os.path.join('#/', buildDir, 'common')

env = env.Clone()
env.Append(CPPPATH = '#/include')

# build libraries
libraries = ['sptCore']

for library in libraries:
    SConscript(os.path.join(library, 'SConscript'), exports='env', build_dir=buildDir)