import os.path

Import('env buildDir')

cxxflags = env['CXXFLAGS']

env = env.Clone(CXXTEST='#/build/cxxtest/cxxtestgen.py', toolpath=['#/build/cxxtest'], tools=['default', 'cxxtest'])
env.Append(CPPPATH=['#/build/cxxtest'])
env.Append(CXXFLAGS=cxxflags)

for library in ['sptCore']:
    env.SConscript(
        os.path.join(library, 'SConscript'),
        exports = ['env'],
        build_dir = os.path.join('#', buildDir, 'tests'))
