import os.path

Import('env buildDir')

cxxflags = env['CXXFLAGS']

env = env.Clone(CXXTEST='#/build/cxxtest/cxxtestgen.py', toolpath=['#/build/cxxtest'], tools=['default', 'cxxtest'])
env.Append(CPPPATH=['#/build/cxxtest'])
env.Append(CXXFLAGS=cxxflags)

env.AppendENVPath('PATH', '#/bin')

for library in ['sptCore']:
    env.SConscript(os.path.join(library, 'SConscript'), exports = ['env'], duplicate = 0)