import os.path

Import('env buildDir')

env = env.Clone(SHLIBPREFIX='', toolpath=['#/build/pypp'], tools=['default', 'pypp'])
env.Append(CPPPATH = ['/usr/include/python2.6'])
env.Append(LIBPATH = ['/usr/lib'])
env.Append(CXXFLAGS=['-DBOOST_PYTHON_DYNAMIC_LIB'])

libraries = ['sptCore']

for library in libraries:
    SConscript(
        os.path.join(library, 'SConscript'),
        exports = ['env'])
