import os.path

Import('env')

# include osg types output for cxxtest
env.Append(CXXTEST_OPTS = "--include=tests/OsgTypeTraits.h")

# for each *.t.h file
for node in Glob('*.t.h'):
    # extract tested class name
    name = os.path.basename(str(node))
    name = name[:name.find('.')]
    # compose test suite name and build it
    env.CxxTest('test_sptCore_' + name, node, LIBS=['osg', 'sptCore'])
