import os.path

Import('env')

cxxflags = env['CXXFLAGS']

env = env.Clone()

def gtest(source, target, env, for_signature):
    result = list()
    for src in source:
        libs = env['LIBS'] if 'LIBS' in env else []
        target = target[0].abspath + env['PROGSUFFIX']
        prog = env.Program(target, source, LIBS=libs+['gtest'], CXXFLAGS=env['CXXFLAGS'])
        action = env.Action(prog[0].abspath)
        result.append(action)
        env.Alias('check', prog, action)

    env.AlwaysBuild('check')
    return result    
    
env.AppendUnique(BUILDERS = {'GTest': Builder(generator = gtest)})
env.AppendENVPath('PATH', '#/bin')

for library in ['sptCore']:
    env.SConscript(os.path.join(library, 'SConscript'), exports = ['env'], duplicate = 0)
