import os.path

Import('env')

env = env.Clone(SHLIBPREFIX='', toolpath=['#/build/pypp'], tools=['default', 'pypp'])

env.Append(CPPPATH = env['PYTHON_INCLUDE'])
env.Append(CXXFLAGS=['-DBOOST_PYTHON_DYNAMIC_LIB'])

libraries = ['sptCore']

for library in libraries:
    SConscript(
        os.path.join(library, 'SConscript'),
        exports = ['env'])
