import sys
import os.path

from SCons import Errors

# select platform
buildDir = os.path.join('build', sys.platform);

# if we don't have scripts for platform report error
if not os.path.exists(os.path.join(buildDir, 'SConscript')):
    raise Errors.UserError("Platform %s is not supported" % sys.platform)

# construct build environment
env = Environment()

# export environment and build dir for other scripts    
Export('env buildDir')

# configure environment and check dependecies platform-wise
env = SConscript(os.path.join(buildDir, 'SConscript'))

# build common library
SConscript('src/SConscript')

# build applications
SConscript('applications/spt/SConscript')
SConscript('applications/sptEditor/SConscript')
SConscript('applications/sptServer/SConscript')