import sys
import os.path

from SCons.Errors import UserError
from build_support import GetPlatform

platform = GetPlatform()

if not platform:
    raise UserError("Unknown platform %s" % sys.platform)

# select platform
buildDir = os.path.join('build', platform);

# if we don't have scripts for platform report error
if not os.path.exists(os.path.join(buildDir, 'SConscript')):
    raise UserError("Platform %s is not supported" % platform)

# construct build environment
env = Environment()

# export environment and build dir for other scripts    
Export('env buildDir')

# configure environment and check dependencies platform-wise
env = SConscript(os.path.join(buildDir, 'SConscript'))

# build common library
SConscript('src/SConscript')

# build applications
SConscript('applications/spt/SConscript')
SConscript('applications/sptEditor/SConscript')
SConscript('applications/sptServer/SConscript')
