Import('env')

objects = env.Object(Split('RailTracking.cpp Track.cpp SwitchableTracking.cpp Switch.cpp Path.cpp Sector.cpp DynamicSector.cpp DynamicScenery.cpp Follower.cpp'))
library = env.StaticLibrary('sptCore', objects);

env.Install('#/lib', library)
