Import('env')

headers = ['RailTracking.h', 'Track.h', 'Path.h']

sources = env.PyPP(target = 'sptCore', source=['#/include/sptCore/' + header for header in headers]+['wrappers.py'])

library = env.SharedLibrary('sptCore', sources, LIBS=Split('boost_python-mt osg sptCore'))
env.Install('#/python', library)
