Import('env')

sources = Split('RailTracking.cpp Track.cpp SwitchableTracking.cpp Switch.cpp Path.cpp Sector.cpp Scenery.cpp Follower.cpp')
library = env.SharedLibrary('sptCore', sources);

env.Install('#/lib', library)
