Import('env')

sources = Split('RailTracking.cpp Track.cpp SwitchableTracking.cpp Switch.cpp Path.cpp Sector.cpp Scenery.cpp Follower.cpp')
library = env.StaticLibrary('sptCore', sources) #, LIBS=['osg']);

env.Install('#/lib', library)
