Import('env')

headers = ['RailTracking.h', 'Track.h', 'Path.h']

sources = env.PyPP(target = 'sptCore', source=['#/include/sptCore/' + header for header in headers])

print repr([str(path) for path in sources])

library = env.SharedLibrary('sptCore', sources, LIBS=Split('boost_python osg sptCore'));
env.Install('#/python', library)
