#!/bin/bash

# If you have nosetests installed, please specify the path to it
# default path:
NOSETESTS_PATH=/usr/bin/nosetests
PYTHON=/usr/bin/python2.7
PYTHONPATH=${PYTHONPATH}:src/

if [[ -x $NOSETESTS_PATH ]]; then
  $NOSETESTS_PATH -v --with-doctest --doctest-extension=rst --with-xunit test/*.py src/sptmath.py doc/*.rst
else
  PYTHONPATH=".:"`pwd`"/src/"
  export PYTHONPATH

  pushd "test"

  $PYTHON t_groups.py
  $PYTHON t_switches.py
  $PYTHON t_tracks.py
  $PYTHON t_scenery.py

  popd

  $PYTHON -m doctest -v sptmath.py
  $PYTHON -m doctest -v doc/sptmath.rst
fi

