#!/bin/bash

# If you have nosetests installed, please specify the path to it
# default path:
NOSETESTS_PATH=/usr/bin/nosetests
PYTHONPATH=".:"`pwd`"/src/"
export PYTHONPATH

if [[ -x $NOSETESTS_PATH ]]; then
  $NOSETESTS_PATH -v --with-doctest test/*.py test/ui/*.py src/
else

  pushd "test"

  python t_groups.py
  python t_switches.py
  python t_tracks.py
  python t_scenery.py
  python t_sptial.py
  python ui/t_views.py

  popd
fi

