from build.support import GetPlatform

Import('env')

platform = GetPlatform()

if platform == 'linux':
    env.Install('#/bin', 'sptEditor')

if platform == 'win32':
    env.Install('#/bin', 'sptEditor.bat')
