import os.path

Import('env')

# include osg types output for cxxtest
for source in Glob('*_t.cpp'):
    target, ext = os.path.splitext(source.abspath)
    env.GTest(target, source, LIBS=['osg', 'sptCore'])
#env.CxxTest('sptCore', ['Sector.t.h', 'Scenery.t.h', 'Follower.t.h', 'Path.t.h'], LIBS=env['LIBS'] + ['osg', 'sptCore'])
