import os.path

Import('env buildDir')

applications = ['spt', 'sptEditor', 'sptServer']

for application in applications:
    SConscript(
        os.path.join(application, 'SConscript'),
        build_dir = os.path.join(buildDir, 'applications', application),
        exports = ['env'])
