import os.path

# import build environment and build directory
Import('env')

env = env.Clone()
env.Append(CPPPATH = '#/include')

# build libraries
libraries = ['sptCore', 'sptGFX']

for library in libraries:
    SConscript(
        os.path.join(library, 'SConscript'), 
        exports=['env']
	)

env.Alias('install', '#/lib')
