import os.path

Import('env buildDir')

# construct buildDir and set include path
applicationDir = 'applications/spt/'
env.Append(CPPPATH = [os.path.join('#', applicationDir, 'include'), '#/include'])
env.Append(LIBPATH = ['#/lib'])

# build
objects = SConscript('src/SConscript', variant_dir = os.path.join(buildDir, 'applications/spt'), duplicate=0)

# link application
program = env.Program(
    'spt' if not env['DEBUG'] else 'sptd', 
    objects, 
    LIBS=['osg', 'osgUtil', 'osgViewer', 'OpenThreads', 'sptCore', 'sptGFX'])

# install it
env.Install('#/bin', program)
