import os.path

Import('env buildDir')

# construct buildDir and set include path
applicationDir = 'applications/spt/'
env.Append(CPPPATH = [os.path.join('#', applicationDir, 'include')])

# build
objects = SConscript('src/SConscript', build_dir = os.path.join(buildDir, applicationDir))

# link application
program = env.Program(
    os.path.join(buildDir, 'spt'), 
    objects, 
    LIBS=['osg', 'osgViewer'])

# install it
prefix = None
env.Install('#/bin' if not prefix else prefix, program)
